"""empty message

Revision ID: 4c380ffb6dab
Revises: None
Create Date: 2015-09-05 20:42:56.140000

"""

# revision identifiers, used by Alembic.
revision = '4c380ffb6dab'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppy')
    op.drop_table('shelter')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('address', sa.VARCHAR(length=250), nullable=True),
    sa.Column('city', sa.VARCHAR(length=80), nullable=True),
    sa.Column('state', sa.VARCHAR(length=40), nullable=True),
    sa.Column('zipCode', sa.VARCHAR(length=10), nullable=True),
    sa.Column('website', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puppy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=16), nullable=False),
    sa.Column('dateOfBirth', sa.DATE(), nullable=True),
    sa.Column('picture', sa.VARCHAR(), nullable=True),
    sa.Column('shelter_id', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.NUMERIC(precision=10), nullable=True),
    sa.ForeignKeyConstraint(['shelter_id'], [u'shelter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
