"""empty message

Revision ID: 7671b3350218
Revises: c53db21a83f4
Create Date: 2016-01-30 22:02:38.128000

"""

# revision identifiers, used by Alembic.
revision = '7671b3350218'
down_revision = 'c53db21a83f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('breed', sa.String(length=32), nullable=True))
    op.drop_column('profile', 'photo')
    op.add_column('puppy', sa.Column('show', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppy', 'show')
    op.add_column('profile', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profile', 'breed')
    ### end Alembic commands ###
