"""empty message

Revision ID: b02cd4bcb33f
Revises: None
Create Date: 2016-01-29 19:34:34.759000

"""

# revision identifiers, used by Alembic.
revision = 'b02cd4bcb33f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adoptors', sa.Column('puppy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'adoptors', 'puppy', ['puppy_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adoptors', type_='foreignkey')
    op.drop_column('adoptors', 'puppy_id')
    ### end Alembic commands ###
