"""empty message

Revision ID: b1cb0fa9b3a8
Revises: dd394eb1a7b5
Create Date: 2016-01-23 11:57:39.521000

"""

# revision identifiers, used by Alembic.
revision = 'b1cb0fa9b3a8'
down_revision = 'dd394eb1a7b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('association', sa.Column('puppy_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'association_puppies_fkey', 'association', type_='foreignkey')
    op.create_foreign_key(None, 'association', 'puppy', ['puppy_id'], ['id'])
    op.drop_column('association', 'puppies')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('puppies', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.create_foreign_key(u'association_puppies_fkey', 'association', 'puppy', ['puppies'], ['id'])
    op.drop_column('association', 'puppy_id')
    op.drop_column('association', 'id')
    ### end Alembic commands ###
