"""empty message

Revision ID: c53db21a83f4
Revises: b02cd4bcb33f
Create Date: 2016-01-29 19:38:25.595000

"""

# revision identifiers, used by Alembic.
revision = 'c53db21a83f4'
down_revision = 'b02cd4bcb33f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'adoptors_puppy_id_fkey', 'adoptors', type_='foreignkey')
    op.drop_column('adoptors', 'puppy_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adoptors', sa.Column('puppy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'adoptors_puppy_id_fkey', 'adoptors', 'puppy', ['puppy_id'], ['id'])
    ### end Alembic commands ###
