"""empty message

Revision ID: dd394eb1a7b5
Revises: 98527a9c89d1
Create Date: 2016-01-22 18:33:19.499000

"""

# revision identifiers, used by Alembic.
revision = 'dd394eb1a7b5'
down_revision = '98527a9c89d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('puppies', sa.Integer(), nullable=True))
    op.drop_constraint(u'association_puppy_id_fkey', 'association', type_='foreignkey')
    op.create_foreign_key(None, 'association', 'puppy', ['puppies'], ['id'])
    op.drop_column('association', 'puppy_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('puppy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.create_foreign_key(u'association_puppy_id_fkey', 'association', 'puppy', ['puppy_id'], ['id'])
    op.drop_column('association', 'puppies')
    ### end Alembic commands ###
