"""empty message

Revision ID: f0c366539147
Revises: 7671b3350218
Create Date: 2016-02-03 17:45:09.664000

"""

# revision identifiers, used by Alembic.
revision = 'f0c366539147'
down_revision = '7671b3350218'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoptors_puppies',
    sa.Column('adoptor_id', sa.Integer(), nullable=False),
    sa.Column('puppy_id', sa.Integer(), nullable=False),
    sa.Column('adopt_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['adoptor_id'], ['adoptors.id'], ),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppy.id'], ),
    sa.PrimaryKeyConstraint('adoptor_id', 'puppy_id')
    )
    op.drop_table('adopters_puppies')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adopters_puppies',
    sa.Column('adoptor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('puppy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['adoptor_id'], [u'adoptors.id'], name=u'adopters_puppies_adoptor_id_fkey'),
    sa.ForeignKeyConstraint(['puppy_id'], [u'puppy.id'], name=u'adopters_puppies_puppy_id_fkey'),
    sa.PrimaryKeyConstraint('adoptor_id', 'puppy_id', name=u'adopters_puppies_pkey')
    )
    op.drop_table('adoptors_puppies')
    ### end Alembic commands ###
